OnlineGroceryShop/OnlineGroceryShop/OnlineGroceryShop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("",include("groceryapp.urls")),
    path('admin/', admin.site.urls),
]

OnlineGroceryShop/OnlineGroceryShop/groceryapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from groceryapp.views import *
from groceryapp.views import home,index,about,main
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('index/', index, name="index"),
    path('about/', about, name="about"),
    path('main/', main, name="main"),
    path('admin-login/', adminLogin, name="admin_login"),
    path('adminhome/', adminHome, name="adminhome"),
    path('admindashboard/', admin_dashboard, name="admindashboard"),
    path('add-category/', add_category, name="add_category"),
    path('view-category/', view_category, name="view_category"),
    path('edit-category/<int:pid>/', edit_category, name="edit_category"),
    path('delete-category/<int:pid>/', delete_category, name="delete_category"),
    path('add-product/', add_product, name='add_product'),
    path('view-product/', view_product, name='view_product'),
    path('edit-product/<int:pid>/', edit_product, name="edit_product"),
    path('delete-product/<int:pid>/', delete_product, name="delete_product"),
    path('registration/', registration, name="registration"),
    path('userlogin/', userlogin, name="userlogin"),
    path('profile/', profile, name="profile"),
    path('logout/', logoutuser, name="logout"),
    path('change-password/', change_password, name="change_password"),
    path('user-product/<int:pid>/', user_product, name="user_product"),
    path('product-detail/<int:pid>/', product_detail, name="product_detail"),
    path('add-to-cart/<int:pid>/', addToCart, name="addToCart"),
    path('cart/', cart, name="cart"),
    path('incredecre/<int:pid>/', incredecre, name="incredecre"),
    path('deletecart/<int:pid>/', deletecart, name="deletecart"),
    path('booking/', booking, name="booking"),
    path('my-order/', myOrder, name="myorder"),
    path('user-order-track/<int:pid>/', user_order_track, name="user_order_track"),
    path('change-order-status/<int:pid>/', change_order_status, name="change_order_status"),
    path('user-feedback/', user_feedback, name="user_feedback"),
    path('manage-feedback/', manage_feedback, name="manage_feedback"),
    path('delete-feedback/<int:pid>/', delete_feedback, name="delete_feedback"),
    path('payment/', payment, name="payment"), 
    path('feedback-read/<int:pid>/', read_feedback, name="read_feedback"),
    path('manage-order/', manage_order, name="manage_order"), 
    path('delete-order/<int:pid>/', delete_order, name="delete_order"), 
    path('admin-order-track/<int:pid>/', admin_order_track, name="admin_order_track"),
    path('manage-user/', manage_user, name="manage_user"),
    path('delete-user/<int:pid>/', delete_user, name="delete_user"),
    path('admin-change-password/',admin_change_password, name="admin_change_password"),
    path('contact/', contact, name="contact"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineGroceryShop/OnlineGroceryShop/groceryapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Carousel(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    def __str__(self):
        return self.title
    
class Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.CharField(max_length=100, null=True, blank=True)
    discount = models.CharField(max_length=100, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name    
    
class UserProfile(models.Model):
    user = models.ForeignKey (User, on_delete=models.CASCADE, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)
   
    def __str__(self):
        return self.user.username
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(default={'objects': []}, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username  


ORDERSTATUS = ((1, "Pending"), (2, "Dispatch"), (3, "On the way"), (4, "Delivered"), (5, "Cancel"), (6, "Return"))
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(default={'objects': []}, null=True, blank=True)
    total = models.CharField(max_length=100, null=True, blank=True)
    status = models.IntegerField(choices=ORDERSTATUS, default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

STATUS = ((1, "Read"), (2, "Unread"))
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username    
    
  
  

OnlineGroceryShop/OnlineGroceryShop/groceryapp/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from .models import Carousel
from .models import Category
from .models import *
from django.contrib.auth import authenticate,login
import json
from django.http import HttpResponse




# Create your views here.
def home(request):
    return render(request, 'home.html')
def index(request):
    return render(request, 'navigation.html')
def about(request):
    return render(request, 'about.html')
def main(request):
    return render(request, 'index.html')

def main(request):
    data = Carousel.objects.all()
    dic = {'data':data}
    return render(request, 'index.html', dic)

def adminLogin(request):
    msg = None
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        try:
            if user.is_staff:
                login(request, user)
                msg = "User login successfully"
                return redirect('admindashboard')
            else:
                msg = "Invalid Credentials"
        except:
            msg = "Invalid Credentials"
    dic = {'msg': msg}
    return render(request, 'admin_login.html', dic)

def adminHome(request):
    return render(request, 'admin_base.html')

def admin_dashboard(request):
    user = UserProfile.objects.filter()
    category = Category.objects.filter()
    product = Product.objects.filter()
    new_order = Booking.objects.filter(status=1)
    dispatch_order = Booking.objects.filter(status=2)
    way_order = Booking.objects.filter(status=3)
    deliver_order = Booking.objects.filter(status=4)
    cancel_order = Booking.objects.filter(status=5)
    return_order = Booking.objects.filter(status=6)
    order = Booking.objects.filter()
    read_feedback = Feedback.objects.filter(status=1)
    unread_feedback = Feedback.objects.filter(status=2)
    return render(request, 'admin_dashboard.html', locals())

def add_category(request):
    if request.method == "POST":
        name = request.POST['name']
        Category.objects.create(name=name)
        messages.success(request, "Category added")
        return redirect('view_category')
    return render(request, 'add_category.html', locals())

def view_category(request):
    category = Category.objects.all()
    return render(request, 'view_category.html', locals())

def edit_category(request, pid):
    category = Category.objects.get(id=pid)
    if request.method == "POST":
        name = request.POST['name']
        category.name = name
        category.save()
        msg = "Category Updated"
    return render(request, 'edit_category.html', locals())

def delete_category(request, pid):
    category = Category.objects.get(id=pid)
    category.delete()
    return redirect('view_category')

def add_product(request):
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        image = request.FILES['image']
        catobj = Category.objects.get(id=cat)
        Product.objects.create(name=name, price=price, discount=discount, category=catobj, description=desc, image=image)
        messages.success(request, "Product added")
    return render(request, 'add_product.html', locals())

def view_product(request):
    product = Product.objects.all()
    return render(request, 'view_product.html', locals())

def edit_product(request, pid):
    product = Product.objects.get(id=pid)
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        try:
            image = request.FILES['image']
            product.image = image
            product.save()
        except:
            pass
        catobj = Category.objects.get(id=cat)
        Product.objects.filter(id=pid).update(name=name, price=price, discount=discount, category=catobj, description=desc)
        messages.success(request, "Product Updated")
    return render(request, 'edit_product.html', locals())

def delete_product(request, pid):
    product = Product.objects.get(id=pid)
    product.delete()
    messages.success(request, "Product Deleted")
    return redirect('view_product')


def registration(request):
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        password = request.POST['password']
        address = request.POST['address']
        mobile = request.POST['mobile']
        image = request.FILES['image']
        user = User.objects.create_user(username=email, first_name=fname, last_name=lname, email=email, password=password)
        UserProfile.objects.create(user=user, mobile=mobile, address=address, image=image)
        messages.success(request, "Registeration Successful")
    return render(request, 'registration.html', locals())


def userlogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, "User login successfully")
            return redirect('home')
        else:
            messages.success(request,"Invalid Credentials")
    return render(request, 'userlogin.html', locals())

def profile(request):
    data = UserProfile.objects.get(user=request.user.id)
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        address = request.POST['address']
        mobile = request.POST['mobile']
        try:
            image = request.FILES['image']
            data.image = image
            data.save()
        except:
            pass
        user = User.objects.filter(id=request.user.id).update(first_name=fname, last_name=lname)
        UserProfile.objects.filter(id=data.id).update(mobile=mobile, address=address)
        messages.success(request, "Profile updated")
        return redirect('profile')
    return render(request, 'profile.html', locals())

from django.contrib.auth import authenticate, login, logout
def logoutuser(request):
    logout(request)
    messages.success(request, "Logout Successfully")
    return redirect('main')


def change_password(request):
    if request.method == 'POST':
        o = request.POST.get('old')
        n = request.POST.get('new')
        c = request.POST.get('confirm')
        user = authenticate(username=request.user.username, password=o)
        if user:
            if n == c:
                user.set_password(n)
                user.save()
                messages.success(request, "Password Changed")
                return redirect('main')
            else:
                messages.success(request, "Password not matching")
                return redirect('change_password')
        else:
            messages.success(request, "Invalid Password")
            return redirect('change_password')
    return render(request, 'change_password.html')

def user_product(request,pid):
    if pid == 0:
        product = Product.objects.all()
    else:
        category = Category.objects.get(id=pid)
        product = Product.objects.filter(category=category)
    allcategory = Category.objects.all()
    return render(request, "user-product.html", locals())

def product_detail(request, pid):
    product = Product.objects.get(id=pid)
    latest_product = Product.objects.filter().exclude(id=pid).order_by('-id')[:10]
    return render(request, "product_detail.html", locals())

def addToCart(request, pid):
    myli = {"objects":[]}
    try:
        cart = Cart.objects.get(user=request.user)
        myli = json.loads((str(cart.product)).replace("'", '"'))
        try:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
        except:
            myli['objects'].append({str(pid):1})
        cart.product = myli
        cart.save()
    except:
        myli['objects'].append({str(pid): 1})
        cart = Cart.objects.create(user=request.user, product=myli)
    return redirect('cart')


def incredecre(request, pid):
    cart = Cart.objects.get(user=request.user)
    if request.GET.get('action') == "incre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
    if request.GET.get('action') == "decre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        if myli['objects'][0][str(pid)] == 1:
            del myli['objects'][0][str(pid)]
        else:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) - 1
    cart.product = myli
    cart.save()
    return redirect('cart')


def cart(request):
    try:
        cart = Cart.objects.get(user=request.user)
        product = (cart.product).replace("'", '"')
        myli = json.loads(str(product))
        product = myli['objects'][0]
    except:
        product = []
    lengthpro = len(product)
    return render(request, 'cart.html', locals())


def deletecart(request, pid):
    cart = Cart.objects.get(user=request.user)
    product = (cart.product).replace("'", '"')
    myli = json.loads(str(product))
    del myli['objects'][0][str(pid)]
    cart.product = myli
    cart.save()

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/add_category.html
{% extends 'admin_base.html' %}
{% block main %}

<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">Add Category</h5>
        <div class="container-fluid">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Category Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Category Name">
                        </div>
                    </div>
                </div>
                <input type="submit" value="Submit" class="m-2 px-3 btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% if msg %}
<script>
    alert('{{msg}}')
</script>
{% endif %}
{% endblock %}

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/add_product.html
{% extends 'admin_base.html' %}
{% block main %}

<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">Add Product</h5>
        <div class="container-fluid">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Product Category</label>
                            <select name="category" class="form-control" required>
                                <option value="">Choose Category</option>
                                {% for i in category %}
                                <option value="{{i.id}}">{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Product Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Category Name">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Product Price</label>
                            <input type="text" name="price" class="form-control" placeholder="Product Price">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Discount</label>
                            <input type="text" name="discount" class="form-control" placeholder="Apply Discount">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Product Image</label>
                            <input type="file" name="image" class="form-control">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="desc" class="form-control" placeholder="write description here"></textarea>
                        </div>
                    </div>
                </div>
                <input type="submit" value="Submit" class="m-2 px-3 btn btn-primary">
            </form>
        </div>
    </div>
</div>

{% endblock %}

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/cart.html
{% load static custom_tags %}
<head>
    <title>My Cart</title>
</head>
{% include 'navigation.html' %}

<div class="container-fluid">
    <div class="container">
        <h2 style="font-family:roman;font-size:bold">
            My Cart
            <a href="/user-product/0/" class="btn btn-warning " style="float:right">Continue Shopping</a>   
            <a href="/booking/" class="btn btn-info mr-2" style="float:right">Buy Now</a>
        <h2>
        <table class="table table-bordered" style="width: 100%">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for i, j in product.items %}
                <tr>
                    <td>
                        <img class="img-thumbnail" src="{{i|productimage}}" alt="product" style="width:100px;height:100px"></a>
                    </td>
                    <td><a href="/product-detail/{{i}}/">{{i|productname}}</a></td>
                    <td>{{i|productprice}}</td>
                    <td style="width:15%">
                        <div class="input-group">
                            <a href="/incredecre/{{i}}/?action=decre" class="btn btn-warning pull-left" id="decrebtn-{{forloop.counter}}">-</a>
                            <input type="text" class="cart-plus-minus-box" type="text" style="width:30%;border:1px solid grey" id="shop_qty-{{forloop.counter}}" name="qtybutton" value="{{j}}" readonly/>
                            <a href="/incredecre/{{i}}/?action=incre" class="btn btn-warning pull-right">+</a>
                        </div>
                    </td>
                    <td id="totalprice-{{forloop.counter}}">{% producttotalprice i j %}</td>
                    <td>
                        <a href="/deletecart/{{i}}/" class="btn btn-danger"><i class="fa fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td colspan="2" id="total-price"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script>
    var prolenth = '{{lengthpro}}';
    var mytotal = 0;
    for(var i=1;i<=prolenth*1;i++){
        totalprice = parseFloat(document.getElementById('totalprice-'+i).innerHTML);
        var mytotal = parseFloat(mytotal) + (totalprice);
    }
    document.getElementById('total-price').innerHTML  = mytotal;
</script>

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/home.html
{% extends 'navigation.html' %}
{% block body %}
<h1>This is home page.</h1>
{% endblock %}

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/manage_order.html
{% extends 'admin_base.html' %}
{% block main %}
{% load custom_tags %}
<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">{{order_status}} Order</h5>
        <div class="container-fluid">
            <table class="table table-bordered table-sm" id="example">
                <thead>
                <tr>
                    <th>S.No.</th>
                    <th>OrderId</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for i in order %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.id}}</td>
                    <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                    <td>{{i.user.username}}</td>
                    <td>
                        {{i.get_status_display}}
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{forloop.counter}}">
                          <i class="fas fa-info"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Order Detail</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                  <table width="100%">
                                      <tr>
                                        <th>Order Id</th>
                                        <td>{{i.id}}</td>
                                        <th>Status</th>
                                        <td>{{i.get_status_display}}</td>
                                      </tr>
                                      <tr style="background:black;color:white">
                                        <th colspan="4">Product Detail</th>
                                      </tr>
                                      {% for j in i.product|get_product %}
                                      <tr>
                                          <th>Product </th>
                                          <td colspan="2">{{j.name}}</td>
                                          <th>
                                            <img src="{{j.image.url}}" style="width:100%;height:80px">
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Quantity</th>
                                          <td>{% get_qty j.id i.id %}</td>
                                          <th>Price(per unit)</th>
                                          <td>Rs. {{j.price}}</td>
                                      </tr>
                                    {% endfor %}
                                      <tr>
                                        <th>Total Price</th>
                                        <td>Rs. {{i.total}}</td>
                                        <th>Booking Date</th>
                                        <td>{{i.created}}</td>
                                      </tr>
                                      <tr>
                                          <th colspan="4" style="background:black;color:white">
                                            <h4>User Detail</h4>
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Name</th>
                                          <td colspan="2">{{i.user.first_name}} {{i.user.first_name}}</td>
                                          <th colspan="1">
                                              <img src="{{i.user.userprofile_set.all.0.image.url}}" style="width:100%;height:80px">
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Email</th>
                                          <td>{{i.user.username}}</td>
                                          <th>Mobile</th>
                                          <td>{{i.user.userprofile_set.all.0.mobile}}</td>
                                      </tr>
                                      <tr>
                                          <th>Address</th>
                                          <td colspan="3">{{i.user.userprofile_set.all.0.address}}</td>
                                      </tr>
                                  </table>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>

                        <a href="/delete-order/{{i.id}}/?action={{request.GET.action}}" class="btn btn-danger"
                           onclick="return confirm('Are You Sure?')">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        <a href="/admin-order-track/{{i.id}}/" class="btn btn-primary" title="Track Status">{{i.get_status_display}}</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

OnlineGroceryShop/OnlineGroceryShop/groceryapp/templates/view_category.html
{% extends 'admin_base.html' %}
{% block main  %}

<div class="card shadow">
    <div class="card-body">

        <h5 class="p-2" style="border-bottom: 2px solid orange;">All Category</h5>
        <div class="container-fluid">

            <table class="table table-bordered table-sm" id="example">
                <thead>
                <tr>
                    <th>S. No.</th>
                    <th>Category Name</th>
                    <th>Creation Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for i in category %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.name}}</td>
                    <td>{{i.created}}</td>
                    <td>
                        <a href="/edit-category/{{i.id}}/" class="text-success">Edit</a>
                        <a href="/delete-category/{{i.id}}/" class="text-danger"
                           onclick="return confirm('Are You Sure?')">Delete</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}